package com.demo.app.service.impl;

import com.demo.app.service.Category;
import org.springframework.stereotype.Component;

import java.util.Arrays;
import java.util.List;
import java.util.Objects;
import java.util.Set;

@Component
public class FoodCategory implements Category {
    private final Set<String> foodCategory = Set.of(
            "BEEF",
            "STEAK",
            "PORK",
            "MUTTON",
            "LAMB",
            "TURKEY",
            "DUCK",
            "CHICKEN",
            "CHICKEN BREASTS",
            "CHICKEN WINGS",
            "CHICKEN THIGHS",
            "SAUSAGE",
            "RIB",
            "HAM",
            "BACON",
            "PIZZA",
            "SPAGHETTI",
            "EGG",
            "FRIED EGG",
            "SCRAMBLED EGG",
            "OMELET",
            "EGGS BENEDICT",
            "POACHED EGG",
            "BOILED EGG",
            "TEA EGG",
            "SANDWICH",
            "HAMBURGER",
            "BREAD",
            "DUMPLING",
            "RICE DUMPLING",
            "HOT POT",
            "OYSTER",
            "SHRIMP",
            "KING PRAWN",
            "LOBSTER",
            "SALMON",
            "COD",
            "SHARK FIN",
            "SQUID",
            "CUTTLEFISH",
            "OCTOPUS",
            "CLAM",
            "CRAB",
            "ABALONE",
            "TUNA",
            "SEAWEED",
            "SEA CUCUMBER",
            "APPLE",
            "PINEAPPLE",
            "BANANA",
            "PAPAYA",
            "GRAPE",
            "STRAWBERRY",
            "KIWI",
            "LONGAN",
            "LITCHI",
            "ORANGE",
            "TANGERINE",
            "MANDARINE",
            "CHERRY",
            "PEACH",
            "CRANBERRY",
            "MANGO",
            "WAX APPLE",
            "DURIAN",
            "PITAYA",
            "GUAVA",
            "POMELO",
            "PASSION FRUIT",
            "HAMI MELON",
            "PUMPKIN",
            "CABBAGE",
            "SPRING ONION",
            "ONION",
            "CARROT",
            "WATER SPINACH",
            "BROCCOLI",
            "SPINACH",
            "CHILI",
            "WHITE FUNGUS",
            "CHINESE CABBAGE",
            "MUSHROOM",
            "ENOKITAKE",
            "CORN",
            "GARLIC",
            "CUCUMBER",
            "POTATO",
            "SWEET_POTATO",
            "EGGPLANT",
            "GINGER",
            "SALT",
            "SUGAR",
            "PEPPER",
            "SOY SAUCE",
            "KETCHUP",
            "MAYONNAISE",
            "MUSTARD",
            "BARBECUE SAUCE",
            "CHILI SAUCE",
            "VINEGAR",
            "SWEET CHILI SAUCE",
            "SYRUP",
            "MILK",
            "COFFEE",
            "BLACK COFFEE",
            "TEA",
            "BLACK TEA",
            "GREEN TEA",
            "HERB JUICE",
            "OOLONG TEA",
            "BUBBLE TEA",
            "WHITE GOURD DRINK",
            "COCOA",
            "SOYBEAN MILK",
            "FRUIT TEA",
            "ORANGE JUICE",
            "APPLE JUICE",
            "GRAPE JUICE",
            "GRAPEFRUIT JUICE",
            "CRANBERRY JUICE",
            "LEMONADE",
            "SUGAR CANE JUICE",
            "WAFFLE",
            "CUPCAKE",
            "MOUSSE",
            "PUDDING",
            "PANNA COTTA",
            "MACARON",
            "TIRAMISU",
            "BROWNIE",
            "FRUIT TART",
            "PUFF",
            "PIE",
            "POUND CAKE",
            "SUNDAE",
            "DOUGHNUT",
            "YOGURT",
            "POPCORN",
            "POTATO CHIPS"
    );

    @Override
    public boolean isExempt(String name) {
        return foodCategory.contains(name.toUpperCase());
    }
}
